export const getLanguageByCode = (code) => {
    switch (code) {
        case "en":
            return "Английский";
        case "ru":
            return "Русский";
        case "ko":
            return "Корейский";
        case "tr":
            return "Турецкий";
        case "de":
            return "Немецкий";
        case "pl":
            return "Польский";
        case "fr":
            return "Французский";
        case "ja":
            return "Японский";
        case "zh":
            return "Китайский";
        case "es":
            return "Испанский";
        case "it":
            return "Итальянский";
        case "sv":
            return "Шведский";
        case "pt":
            return "Португальский";
        case "fl":
            return "Филипинский";
        case "el":
            return "Греческий";
        case "id":
            return "Индонезийский";
        case "da":
            return "Датский";
        case "nl":
            return "Нидерландский";
        case "bs":
            return "Боснийский";
        case "hr":
            return "Хорватский";
        case "fi":
            return "Финский";
        case "cs":
            return "Чешский";
        case "sq":
            return "Албанский";
        case "ro":
            return "Румынский";
        case "vi":
            return "Вьетнамский";
        case "sk":
            return "Словацкий";
        case "az":
            return "Азербайджанский";
        case "uk":
            return "Украинский";
        case "no":
            return "Норвежский";
        case "hu":
            return "Венгерский";
        case "bg":
            return "Болгарский";
        case "be":
            return "Белорусский";
        case "ka":
            return "Грузинский";
        default:
            return "Английский";
    }
};
